# Generated by Django 5.1.3 on 2024-11-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_admission',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=255, null=True),
        ),
    ]
