# Generated by Django 5.0 on 2024-11-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.level",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.question"
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="profiles.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.question"
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.subject"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.subject",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.subject"
            ),
        ),
    ]
