# Generated by Django 5.0 on 2024-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="questions"),
        ),
    ]
